### ISSUE TITLE
Listing for all projects from a Github user

### ISSUE THREAD

**Issue by brandonpittman** [inch-ci/inch_ci-web#10]
It would be useful to have a page listing all the projects that have been registered with Inch-CI for a particular Github user.

![screen shot 2014-06-04 at 10 52 54 am](https://cloud.githubusercontent.com/assets/967145/3184333/38c0ff6c-ec82-11e3-9ab5-ca79a54104a3.png)

**Comment by rrrene** [comment]
@brandonpittman this suggestion is really old, apologies for that. 

I've finally come around to implement "Sign in with GitHub" during the holidays. It basically does what this issue is about --> list all your projects in an overview.
