### ISSUE TITLE
Page not found if "/" is in branch name

### ISSUE THREAD

**Issue by TheLonelyGhost** [inch-ci/inch_ci-web#103]
As title suggests, the branch "feature/documentation" would evaluate to http://inch-ci.org/github/thelonelyghost/dandelion/branch/feature/documentation. That url doesn't exist.

---
Re: [TheLonelyGhost/dandelion](http://inch-ci.org/github/thelonelyghost/dandelion)

**Comment by rrrene** [comment]
I am so sorry for not getting back to you about this. :cry: It got literally lost in the mail after my talk about Inch at EuRuKo. 

Works now. :+1: http://inch-ci.org/github/thelonelyghost/dandelion?branch=feature%2Fdocumentation

**Comment by TheLonelyGhost** [comment]
:+1: Much appreciated!
