### ISSUE TITLE
Link issues

### ISSUE THREAD

**Issue by rugk** [inch-ci/inch_ci-web#104]
Some links which are incorrect. (also for http://trivelop.de/ as I could not find a repo for the web site)

page | where | incorrect link | problem/correct link
------ | -------- | ---------------- | --------------------------
main page|bottom|[Blog](http://trivelop.de/imprint/) | links to imprint
http://trivelop.de/|right| Fork on GitHub| links to your profile
http://trivelop.de/imprint/|Twitter links| https://github.com/rrrene| link to your GitHub profile

**Comment by rrrene** [comment]
Thx for all the bug reports! i will do my best to fix them during the coming week! :+1:
