### ISSUE TITLE
Suggests specification of return type of setters (#meth=)

### ISSUE THREAD

**Issue by paddor** [inch-ci/inch_ci-web#109]
The return value of those kinds of method is enforced by ruby to be exactly the object given as parameter. Maybe you could deduce it from the parameter's documentation or just stop suggesting this on setter methods.

**Comment by rrrene** [comment]
Good catch! I will try to update Inch over the holidays :+1:

**Comment by paddor** [comment]
Thank you. :-) Enjoy the holidays!

**Comment by paddor** [comment]
Any news on this?

Also, it seems like refreshing doesn't work anymore...

**Comment by rrrene** [comment]
Hi, I'm on it. Server clogged up somehow. :scream: 

Had a nasty cold over the holidays and then ... forgot. Sorry. :sweat:

**Comment by paddor** [comment]
Oh no, very sorry to hear that.

Take your time. :-)

**Comment by paddor** [comment]
Thanks a lot! :+1:

**Comment by rrrene** [comment]
Hey, this is not live yet. I am re-opening the issue to not forget it.

(I have to make a new release of Inch and point Inch CI to it. Won't get that done today, unfortunately.)

**Comment by paddor** [comment]
Oops :sweat_smile: All I did was test is the Refresh button and verify whether Inch CI suggests setting a `@return` on setter methods. And it doesn't, which I like. So what else is there to come?

**Comment by paddor** [comment]
Any updates?

**Comment by rrrene** [comment]
Not sure, I am a bit out of the loop on my Github Issues as there is currently soooo much work. :scream: 

Does Inch CI now behave the way you suggested?

**Comment by paddor** [comment]
I just checked! Yes, it does. No more suggestions for return type on `#foo=` methods. Thank you!
