### ISSUE TITLE
trying to build Inch CI for an organization public github repo fails

### ISSUE THREAD

**Issue by nicb** [inch-ci/inch_ci-web#114]
Hi, wonderful project!

I logged in with my `github` account and then tried to build the documentation evaluation for an organization I belong to (*SMERM*) and I get an error:

https://inch-ci.org/github/SMERM/EMUForm?pending_build=166300

I get the "We're sorry, but something went wrong. If you are the application owner check the logs for more information." page.

I have granted access to the organization to *Inch CI* and in fact, the build succeeds when I am not logged in. The problem is that I can't have a badge this way.

I have looked up the issues but no one seems to mention this problem, so I opened a new one.
Thank you for your time.

**Comment by rrrene** [comment]
> I get the "We're sorry, but something went wrong. ..." page.

I am currently wading through the log files to identify what went wrong.

So you're basically describing that you get an error as a logged in user whenever you visit the project page [0]? Or does this *only* happen when you rebuild the project?

[0] https://inch-ci.org/github/SMERM/EMUForm

> The problem is that I can't have a badge this way.

You should be able to get the badge by clicking on the badge (even if not logged in).
![image](https://cloud.githubusercontent.com/assets/311914/12872753/7dea3782-cdab-11e5-835e-7bea6d15166f.png)

**Comment by nicb** [comment]
Wow! What a quick service! Thank you Ren&eacute;!

Ok, I will do as you say - still I thought it would be useful to signal the problem to you... Thanks again, especially for the great project. Feel free to ask me for tests and reproducing the problem if you need it.

**Comment by mockdeep** [comment]
@rrrene I'm seeing similar errors. When I tried to add a public repo I just got a generic "something went wrong error". I see the same error when I follow your link above, or try to visit another project's page, such as [rubocop](http://inch-ci.org/github/bbatsov/rubocop).

![inchy](https://cloud.githubusercontent.com/assets/80543/13036369/82b7e29a-d31a-11e5-9b0f-2e0c9d565399.png)

**Comment by mockdeep** [comment]
I logged out and added the project, and everything seems to work fine. It looks like it's only a problem when logged in.

**Comment by rrrene** [comment]
Okay, I found a way to reproduce this. :tada:  

Will have to find some time to dig deeper. Sorry for taking so long, :cry:  but I'm drowning in work/family/academic stuff at the moment.

**Comment by rrrene** [comment]
@nicb @mockdeep Fixed it! Thanks again for reporting! :+1:
