### ISSUE TITLE
Seems confused by ES6 modules

### ISSUE THREAD

**Issue by kasperisager** [inch-ci/inch_ci-web#116]
For some reason in http://inch-ci.org/github/kasperisager/doem both ES6 exported functions (`export default ...`) and the CJS exports `module.exports` show up for the same functions. I remember this not being the case when I initially set up the project. Any ideas as to what the issue might be?

**Comment by rrrene** [comment]
Mmmh, actually I have no idea. I've had problems with ES6 from the beginning. Guess I will have to spend some time with the JS implementation of Inch (in order to figure this out).

Thx for the report! :+1:

**Comment by kasperisager** [comment]
This seems to have been fixed so I'll go ahead and close it 🎉
