### ISSUE TITLE
builds stuck

### ISSUE THREAD

**Issue by sagiegurari** [inch-ci/inch_ci-web#117]
I actually didn't change my code, so something changed in your backend.
See: http://inch-ci.org/github/sagiegurari/node-spider-script/builds
The last 2 builds there are stuff on running forever.

**Comment by rrrene** [comment]
Fixed it. Thanks for the bug report! :+1:

**Comment by sagiegurari** [comment]
thanks, works.
but if you check all builds link in your site, you will see some builds are still 'running' (i'm sure they are not).
http://inch-ci.org/github/sagiegurari/node-spider-script/builds
doesn't bother me, but just check something is not stuck in your server process and consuming cpu/memory.

**Comment by rrrene** [comment]
Ah, that's a UI issue.

The builds are dead and already marked as such, but the JS timers are counting up nonetheless.

**Comment by panzerdp** [comment]
Hi @rrrene,
Thanks for this useful service. :+1: 

I have the same problem. Some builds are stuck and run forever.
http://inch-ci.org/github/panzerdp/voca/builds

What could be the problem?
Thanks.

**Comment by rrrene** [comment]
@panzerdp I'm not sure. I ran my usual checklist and now I am a bit out of ideas. o_O

Sorry, but this might take a while, since I'm swamped with work right now :disappointed:
