### ISSUE TITLE
Add support for Erlang

### ISSUE THREAD

**Issue by manuel-rubio** [inch-ci/inch_ci-web#124]

**Comment by rrrene** [comment]
Hi there, sorry for not getting back to you.

Is there a doc-generation in Erlang like e.g. JavaDoc in Java?

**Comment by manuel-rubio** [comment]
Hi @rrrene in Erlang you can use EDoc. Here is a link about the tool:

http://erlang.org/doc/apps/edoc/chapter.html

**Comment by erszcz** [comment]
It would be really cool to see this happening! The Erlang ecosystem needs a boost with regard to code documentation.
