### ISSUE TITLE
Image broken on the learn_more section page

### ISSUE THREAD

**Issue by gaetanm** [inch-ci/inch_ci-web#132]
Hey,

An image is not displayed on this page: http://inch-ci.org/learn_more.

Here is a screenshot:
![screen shot 2016-05-27 at 12 29 29](https://cloud.githubusercontent.com/assets/2548394/15605563/ecacb1a2-2406-11e6-8b29-b53dfc6bddf1.png)

(Tested on Safari and Chrome on OS X.)

**Comment by rrrene** [comment]
Good catch! :+1:

**Comment by rrrene** [comment]
Fixed.
