### ISSUE TITLE
Link to badges is broken on project page

### ISSUE THREAD

**Issue by MasterRoot24** [inch-ci/inch_ci-web#134]
@rrrene As requested [on Twitter](https://twitter.com/rrrene/status/737177815011971072) :blush: .

The link on the project page to allow a user to get the different types of badges is broken and takes me to `/` and if I go back to the project page again and click on the link I get taken back `/` in a loop.

![cjqiqxdweaaodv5](https://cloud.githubusercontent.com/assets/7666402/15645545/023f9146-2651-11e6-9bbc-e47a6b60b172.jpg)

I've forked the repo and I attempted to fix the issue so that I could submit a PR, but although I found where the broken link is, I'm not sure where it should actually point to.

The locations of the broken link: [here(en)][en-link] and [here(fr)][fr-link].

[en-link]: https://github.com/inch-ci/inch_ci-web/blob/master/config/locales/en.yml#L439
[fr-link]: https://github.com/inch-ci/inch_ci-web/blob/master/config/locales/fr.yml#L131

**Comment by rrrene** [comment]
Yeah, so if I remember correctly the thinking was that you clicked on a badge on GitHub and if wanted to have your own, you could go to the frontpage and enter your project into the input field there.

In any other project this would link to a login page, right? :sweat_smile:

**Comment by MasterRoot24** [comment]
Sorry, I'm not sure I follow.

If I'm looking at a project in InchCI ([this one](https://inch-ci.org/github/MasterRoot24/cloudiary) for example), to me the section "Can I have my own badges?" should contain information on how to get my own badges. The link in that section just takes me to the main page where, as you said, a user can enter their project. But that doesn't tell me how to "get my own badges".

Hope I've explained that clearly enough...

**Comment by rrrene** [comment]
Ah, I misinterpreted the intial question. Sorry!

I saw you already put [your badge in your README](https://github.com/MasterRoot24/cloudiary). What exactly do you think "getting your own badges" should give you besides the badge for your project? Or is it just that this link does not make much sense for logged in users who already use the service?

**Comment by MasterRoot24** [comment]
Yeah, I copied the Markdown syntax from another repo and just changed the user/repo in the URL to get it into my README as I couldn't find where I could get the Markdown for the badge from.

> What exactly do you think "getting your own badges" should give you besides the badge for your project?

When I click the link in question, I expect to see something like this from TravisCI for example:
<img width="619" alt="screen shot 2016-05-31 at 21 51 19" src="https://cloud.githubusercontent.com/assets/7666402/15690105/df8c75ea-2779-11e6-9138-c14742652f90.png">

That's what I expected to see when I clicked this link:
![cjqiqxdweaaodv5](https://cloud.githubusercontent.com/assets/7666402/15645545/023f9146-2651-11e6-9bbc-e47a6b60b172.jpg)

**Comment by rrrene** [comment]
That's what I thought. The text might be misleading for logged in users looking at their own project.

Just to be clear: You get the "Status Image" dialog by clicking on the badge on the top of the page. Just like you did on Travis CI.

**Comment by MasterRoot24** [comment]
Ah! Totally didn't spot that button was clickable at the top! 😆

Do you feel that the text should be changed for logged in users so that it's not as misleading? Or is it ok as it is and this is a non-issue? I can't help I'm not the only one confused by it. Then again...

**Comment by rrrene** [comment]
No no, this is absolutely a valid issue! I just wanted to understand the confusion first, so we can decide on a solution.

If you have any suggestion besides the (trivial) text change, I all ears!

**Comment by MasterRoot24** [comment]
The best I can come up with right now:

```erb
<h2>Can I have my own badges?</h2>
<p>
Yes, sure!
<% if logged_in %>
  <%# The link below would show the "Status Image" dialog %>
  Click here learn how to get your badge.
<% else %>
  <%# The link below would take the user to root_path to allow them to sign up %>
  Click here to sign up and get started.
<% end %>
</p>
```
Note: I'm not sure the syntax above is 100% - I just bashed it in to give an idea of what I envisaged.

**Comment by rrrene** [comment]
I had already updated the text in the meantime: http://inch-ci.org/github/pry/pry

Do you think this works as well?

**Comment by MasterRoot24** [comment]
Ah! Yeah, I think that's a lot clearer. Thanks! 👍

**Comment by rrrene** [comment]
Cool! Thanks for raising the issue! Inch CI is very much a community project and thrives on critical feedback :sweat_smile:
