### ISSUE TITLE
builds stopped working

### ISSUE THREAD

**Issue by sagiegurari** [inch-ci/inch_ci-web#138]
both via web UI or via github webhooks.
see example project:
http://inch-ci.org/github/sagiegurari/simple-oracledb/builds

thanks

**Comment by rrrene** [comment]
Somehow this happens every blue moon with JS projects. I will have to log some more debugging info.

Fixed now. Thx for reporting! :+1:

**Comment by sagiegurari** [comment]
thanks, but I hope you got that debugging info there already because manual refresh doen't work :)
