### ISSUE TITLE
add support for melonJS

### ISSUE THREAD

**Issue by obiot** [inch-ci/inch_ci-web#153]
Hi, despite melonJS (https://github.com/melonjs/melonJS) being a javascript engine/library, the language is not properly recongized :

````
It seems like your project's language is not supported (yet).

Currently Inch supports Elixir, JavaScript, and Ruby.

If your language of choice is not supported, create an issue or drop me a line on Twitter.
````

thanks ! :)

**Comment by rrrene** [comment]
GitHub misrepresents this project as CSS. You should be able to change the language yourself: 

![image](https://cloud.githubusercontent.com/assets/311914/20192251/6034de78-a789-11e6-9215-b2dd2b3bfa81.png)

**Comment by obiot** [comment]
yes, but once signed in, the option is no more available : 

![image](https://cloud.githubusercontent.com/assets/4033090/20201970/d9ba2d94-a7f6-11e6-9e9e-1911a5d06a3e.png)

**Comment by rrrene** [comment]
Wuatttt? 😱 

Okay, I will investigate!

**Comment by obiot** [comment]
I see that it works now, so thanks !
