### ISSUE TITLE
JS builds stopped working

### ISSUE THREAD

**Issue by sagiegurari** [inch-ci/inch_ci-web#155]
both via web UI or via github webhooks.
see example project:
http://inch-ci.org/github/sagiegurari/simple-oracledb/builds

thanks

(by the way I copy pasted from #138 which was the last time the 'blue moon' happened)

**Comment by rrrene** [comment]
In my defense: I have been searching for the error since yesterday and it has been a different (sysadmin) issue than last time. I will try to move this to a leaner/easier setup over the holidays.

As always: Thanks for the heads up. :+1:

**Comment by sagiegurari** [comment]
:+1:  thanks
Only bugging you because I love the tool :)
