### ISSUE TITLE
project is recognized as html but is js

### ISSUE THREAD

**Issue by HansHammel** [inch-ci/inch_ci-web#163]
https://github.com/HansHammel/license-compatibility-checker

There is a huge HTML file in the project. First GitHub's recognition was also wrong. I corrected this using .gitattributes file with apropriate linguist setting, then tried to move the HTML file into a dot-folder, but InchCI is still recognizing the project as HTML. See the screenshots...

![image](https://cloud.githubusercontent.com/assets/6475700/21719687/602466fc-d41f-11e6-8f1a-ebe9bdfdc873.png)

 
![image](https://cloud.githubusercontent.com/assets/6475700/21719845/0dd620b0-d420-11e6-9667-b7f5de725008.png)

Thanks.

**Comment by rrrene** [comment]
can you use the "change" link next to "HTML" on the Inch CI project page?

**Comment by HansHammel** [comment]
Sorry I have no login.

**Comment by rrrene** [comment]
Wow, that sounds a bit pretentious, but I guess sometimes stuff gets "lost in translation" over the internet.

I fixed your repo on Inch CI for you. :+1:

**Comment by HansHammel** [comment]
Pretentious!? Thanks, anyway.

**Comment by rrrene** [comment]
@HansHammel well it sounded strange to say "I want to use this software, but I do not want to login to use this software". But as I said: Maybe you have your reasons for not wanting to login and sometimes stuff comes off wrong over the internet. No harm, no foul. :neckbeard: :+1:

**Comment by HansHammel** [comment]
Well, René. I am no big fan of this login madness. And, as our case demonstrates, there is no need for a login to consume this service. Btw, I like to seperate things anyway. So InchCI is doing it right. 

Let me ask one more thing. As a German, form a legal point of view, what do you think of all this singin-with-github services in terms of private repositories, e.g. commissional work and customer data, and the safe harbour verdict!?
