### ISSUE TITLE
parser fails on js project

### ISSUE THREAD

**Issue by sagiegurari** [inch-ci/inch_ci-web#164]
something changed and now the parser is failing and it is not checking the docs anymore.

You can see here for an example
https://inch-ci.org/github/sagiegurari/event-emitter-enhancer/builds

**Comment by rrrene** [comment]
Yeah ... DNS changes propagated slowly, so some jobs landed on the old server.

The good news here is: New Server 🎉 Yay!

P.S. Parser is working (again).

**Comment by sagiegurari** [comment]
Thanks. Working good 👍
