### ISSUE TITLE
git commits no longer trigger automatic doc check

### ISSUE THREAD

**Issue by sagiegurari** [inch-ci/inch_ci-web#168]
It used to work, maybe with the updated site it stopped.
basically now I have to run it manually.

**Comment by sagiegurari** [comment]
any updates on this one?

**Comment by rrrene** [comment]
@sagiegurari Hi, sorry for not replying. I checked this when you first reported it, but to me it seems that all GitHub web hooks are executed as expected. Did I misunderstand something?

**Comment by sagiegurari** [comment]
So for me the githooks are not running or not triggering the inch build.
This started after the new website change. anything I need to do on my end to make it work again?

**Comment by sagiegurari** [comment]
got into a repo webhooks and I see that the inch webhook returns 301 responses (redirect)
http://inch-ci.org/rebuild
so it is failing.

**Comment by sagiegurari** [comment]
ok so I deleted the webhooks but i'm unable to add it via inch website, keeps telling me something is wrong.
Added it manually and now it works.
So i'll have to do it manually for all repos but this is something you should check.

**Comment by sagiegurari** [comment]
dug into this a little bit more and the issue is that the old webhook was http and the new is https.
when going to http I guess you are now redirecting to https and github doesn't follow redirects (which i think is ok from their part).

**Comment by rrrene** [comment]
Excellent analysis, that fixed it. Thanks for digging so deep! :+1:
