### ISSUE TITLE
js builds not starting

### ISSUE THREAD

**Issue by sagiegurari** [inch-ci/inch_ci-web#178]
seems that builds are getting scheduled by git and manual but just not starting up.

https://inch-ci.org/github/sagiegurari/js-project-commons/builds

**Comment by rrrene** [comment]
Did this sort itself out or is there still a problem with the evaluation? 

Because it seems fine to me for the link you provided (the green check mark meaning success):

![image](https://cloud.githubusercontent.com/assets/311914/23121575/3f2c8500-f761-11e6-935e-8950b4301ed2.png)

**Comment by sagiegurari** [comment]
ya, seems you are right, it did resolve at the end automatically (didn't check until you responded now).
so i'm closing this issue.
thanks
