### ISSUE TITLE
Deleting my account and projects

### ISSUE THREAD

**Issue by JoeNyland** [inch-ci/inch_ci-web#179]
How do I delete my Inch CI account and the projects I have added within it?

**Comment by rrrene** [comment]
By creating an issue on GitHub, like you did.

Please explicitly state that you want your data deleted ("Please delete my data") and I will see to it :+1:

**Comment by JoeNyland** [comment]
Ok, please delete my data.

I changed my GitHub account username yesterday from MasterRoot24 to JoeNyland, in case that helps...

**Comment by rrrene** [comment]
I deleted everything, but as long as you have the Inch CI badges referenced in your READMEs, requesting those images will always trigger a build for the requested repo. If the repo still exists AND is open-source, then it will be re-added to Inch CI.

**Comment by JoeNyland** [comment]
Ok, thanks. I'll update the READMEs and remove those badges.
