### ISSUE TITLE
Docs for MessagesController

### ISSUE THREAD

**Issue by Br3nda** [inch-ci/inch_ci-web#185]
---
Re: [U] [MessagesController](http://inch-ci.org/github/wharehauora/wharehauora-server/revision/17e9e05c/code_object/11380813?branch=master) in [WhareHauora/wharehauora-server](http://inch-ci.org/github/wharehauora/wharehauora-server)

**Comment by rrrene** [comment]
Hi, I guess you misread 

> Please help! Open an issue on GitHub if this assessment is incorrect.

and wanted to create an issue in your own project to remind yourself to enhance the documentation.

If I am wrong, please re-open this issue! :+1:
