### ISSUE TITLE
inch.json seems to be ignored

### ISSUE THREAD

**Issue by tomlutzenberger** [inch-ci/inch_ci-web#191]
I added an `inch.json` to my repo and after refreshing the excluded files are still in the report.

---
Re: [rbutrcom/rbutr-browser-extension](http://inch-ci.org/github/rbutrcom/rbutr-browser-extension)

**Comment by tomlutzenberger** [comment]
Nevermind, the "issue" solved itself. It just took a bit more time than expected until it refreshed.

**Comment by rrrene** [comment]
@tomlutzenberger :+1: yeah, some builds are taking a bit longer than usual. I will have to check that as soon as I find the time (Inch CI is very much a side-project).
