### ISSUE TITLE
"This is not evaluated yet. Press refresh to evaluate now!"

### ISSUE THREAD

**Issue by AlphaMycelium** [inch-ci/inch_ci-web#198]
I get this message every time I try to build my project. So I click refresh, it builds - then shows the same message again! Why is it saying this, and how can it be fixed?

**Comment by jayvdb** [comment]
I also see this, when creating a new project.
It looks like inch-ci is broken at the moment.

**Comment by krabique48** [comment]
eeh. same here

**Comment by leoarnold** [comment]
Kinda same [here](https://inch-ci.org/github/leoarnold/puppet-cups): Whether I hit refresh or trigger the rebuild hook, the inch build is scheduled but never executed.

**Comment by tripu** [comment]
Same here.

**Comment by leoarnold** [comment]
I think it's working again for everybody and we can close this. Please check.

**Comment by tripu** [comment]
Seems to be working okay for me now, yes.

**Comment by danth** [comment]
Ah sorry, wasn't keeping up-to-date on this issue. Will close now.
