### ISSUE TITLE
Incorrect assessment when having large copyright headers

### ISSUE THREAD

**Issue by linki** [inch-ci/inch_ci-web#31]
Some projects use large comment section in the top of each file to print copyright information. This confuses inch-ci and leads to a good documentation score where in fact it is not.

---
example from OpenProject:
Re: [A] [WorkPackagesController](http://inch-ci.org/github/opf/openproject/branch/dev/revision/4da4c61c/code_object/225454) in [opf/openproject](http://inch-ci.org/github/opf/openproject)

**Comment by rrrene** [comment]
@linki sorry for never getting back to you. 

I looked into this at the time and the problem is that I don't see any way to differentiate between copyright headers and legit inline-docs comments. If you have any idea how to make this work: do not hesitate to suggest a solution!
