### ISSUE TITLE
My repository page is 500.

### ISSUE THREAD

**Issue by JuanitoFatas** [inch-ci/inch_ci-web#40]
Sorry, I have many repositories. :sweat: 

http://inch-ci.org/github/JuanitoFatas

**Comment by jnbt** [comment]
Normally you have to include your repo into the URL, e.g.:

http://inch-ci.org/github/juanitofatas/comer_de_tapas

**Comment by JuanitoFatas** [comment]
Yea, thanks for the heads up but there are some links guide me to http://inch-ci.org/github/juanitofatas/.

**Comment by rrrene** [comment]
@jnbt We have GitHub signin now. The URL is Juanito's user profile :wink: 

@JuanitoFatas Thanks for the bug report! Your profile should now be ok. Maybe hit the "Sync now!" button to ensure everything is up-to-date.

**Comment by JuanitoFatas** [comment]
> Your profile should now be ok. Maybe hit the "Sync now!" button to ensure everything is up-to-date.

Awesome! Thank you for a prompt fix :kissing_heart:
