### ISSUE TITLE
Does Inch CI recognize `.inch.yml` configuration in repos?

### ISSUE THREAD

**Issue by s3ththompson** [inch-ci/inch_ci-web#43]
If so, you might want to add a blurb about configuration support on the Inch CI pages?

**Comment by rrrene** [comment]
That is certainly something I should do :smile: 

Thanks for the heads-up, will add a help section for that!

**Comment by s3ththompson** [comment]
Awesome. Thanks!  Great project, by the way--I love the design of Inch.
