### ISSUE TITLE
Build failure due to `checkout_revision`

### ISSUE THREAD

**Issue by splattael** [inch-ci/inch_ci-web#53]
Hi René,

Inch builds for ROM a failing since 6 days:
http://inch-ci.org/github/rom-rb/rom/builds

![inch rom](https://cloud.githubusercontent.com/assets/28908/6367457/ad11a4a8-bcd3-11e4-8fd0-3df6d8f9cf9b.png)

Hovering of the red question mark it says `failed:revision_failed`

Can you help? :)

Kind regards,
  Peter

**Comment by rrrene** [comment]
Fixed it https://inch-ci.org/github/rom-rb/rom/builds :tada: 

Thanks!

**Comment by splattael** [comment]
Yay, thank you for your :zap: fast response!
