### ISSUE TITLE
[JS] Project analysis fails even with inch.json file

### ISSUE THREAD

**Issue by MattiSG** [inch-ci/inch_ci-web#55]
I try to analyse sgmap/meteor-assemblee-nationale, but [the build always fails](https://inch-ci.org/github/sgmap/meteor-assemblee-nationale/builds), even after adding an `inch.json` config file telling Inch where to look.

What can I do?

**Comment by rrrene** [comment]
Thanks for the heads up! :+1: 

I fixed it in InchJS 0.2.16 --> https://inch-ci.org/github/sgmap/meteor-assemblee-nationale/branch/inch-ci

**Comment by MattiSG** [comment]
You rock  :)

**Comment by MattiSG** [comment]
By the way, can I use the `.inch.yml` syntax with a JS project? I prefer that syntax (both for file invisibility and format), and it would probably be easier to have only one way to configure Inch.

**Comment by rrrene** [comment]
At present, no. But you could create an issue in the InchJS project and I will consider it for the future :wink:
