### ISSUE TITLE
Incorrect Assessment for TomDoc

### ISSUE THREAD

**Issue by fny** [inch-ci/inch_ci-web#60]
Doc:

```
Converts the specified predicate method to a bang method. Beware: bang
methods will be created for undefined methods too. Assignment methods (`method=`)
and bang methods (`method!`) will not be converted.

klass - The Class to target for bangification
predicate_method - The Symbol of the predicate method
block - An optional block to run if a predicate method returns something falsey

Options

  matching - The Regexp used to match methods that should be bangified
  prefix - The String prefix to add to front of the bangified method
  suffix - The String suffix to add to end of the bangified method

Returns the Symbol name of the bang method created or nil if the method
was not bangified (ends in `!` or `=`.)
```

Method Signature: `def bangify_method(klass, predicate_method, prefix: '', suffix: '')`

Suggestions given:

 - Describe what "bangify_method" returns.
 - Describe the parameter "suffix".
 - Describe the parameter "prefix".

---
Re: [B] [Interrobang#bangify_method](http://inch-ci.org/github/fny/interrobang/branch/master/revision/d95d244d/code_object/910171) in [fny/interrobang](http://inch-ci.org/github/fny/interrobang)

**Comment by rrrene** [comment]
Thank you very much for the bug report! :+1: 

I fixed the two parameters which where not detected correctly. As for the "Describe what the function returns" - this technically correct, as [TomDoc requires you to indent the last line](https://github.com/mojombo/tomdoc/blob/master/tomdoc.md#returns):

> Lines SHOULD be wrapped at 80 columns. Wrapped lines MUST be indented, as a block, under the parent line by at least two spaces.

**Comment by fny** [comment]
Thanks for the tip. :)
