### ISSUE TITLE
Javascript parsing failed

### ISSUE THREAD

**Issue by jlchereau** [inch-ci/inch_ci-web#78]
![image](https://cloud.githubusercontent.com/assets/2556751/7836897/dcac81de-047b-11e5-811d-7340f713692b.png)
---
Re: [Memba/Memba-Blog](https://inch-ci.org/github/Memba/Memba-Blog)

**Comment by rrrene** [comment]
Okay, what happened is this: There was a bug in InchJS. 

1. InchJS uses JSDoc for parsing and the bug caused JSDoc to analyse everything in your repo (including the public/assets/ javascripts).
2. This took veeeeeery long and made the process very memory-heavy (as in: gigs of memory).
3. A GitHub user called "Membabot" made about 150 commits to your repo.
4. This scheduled ~ 150 evaluations on the Inch CI server.
5. The server basically overDOSed himself.

I patched InchJS and now everything is fine. Your badge now also generates as promised: [![Inline docs](http://inch-ci.org/github/Memba/Memba-Blog.svg?branch=master)](http://inch-ci.org/github/Memba/Memba-Blog)

Thanks for the heads-up! :+1:

**Comment by jlchereau** [comment]
Thx!
