### ISSUE TITLE
Explain better about languages support

### ISSUE THREAD

**Issue by igorsantos07** [inch-ci/inch_ci-web#79]
I've stumbled upon Inch-CI in a JS project README file. Opened it, read the about page, and gave it a try with a PHP repository. After a while it gave me no results at all. I started wondering if it was because of the language, fiddled around the site and noticed at the home page it only supports Ruby (duh, it's based on it) JS (duh, just saw a project with it) and Elixir.

Would be nice and easier for newcomers if there was info about supported languages in the About page, as well as a notice when you try to add a project to Inch-CI that is not supported - instead of running a build over something it won't even work.

**Comment by rrrene** [comment]
Good point! :+1: 

Will fix in next release!

**Comment by rrrene** [comment]
Done!

https://inch-ci.org/learn_more

**Comment by igorsantos07** [comment]
Cool!
But what about a helpful explanation / hint on the project page? If you try to analyse a non-supported project it will still take a while analysing and then bring you an empty report, with "no apparent reason".

**Comment by rrrene** [comment]
Hi, I added the hint: https://inch-ci.org/github/igorsantos07/Gii-Templates

Do you have any suggestions for the phrasing?

**Comment by igorsantos07** [comment]
Man, never saw this ticket being closed. Sorry!
It seems cool, thanks! :)
