### ISSUE TITLE
Web Hook from website

### ISSUE THREAD

**Issue by chrilith** [inch-ci/inch_ci-web#80]
Hi,

I just added this great stuff to my project!

Now, it is supposed to be possible to auto add a web hook by signing in with my GitHub account. But once on my Inch CI profile, I don't see the way to enable the auto update.

Of course I can configure it in GitHub as stated here http://inch-ci.org/help/webhook but I'd like to understand how to do it directly from Inch CI.

Any clue?

Thanks!

**Comment by rrrene** [comment]
Oh crap!

That was a complete oversight by me ... it is fixed now. Thanks a million for the heads up!

**Comment by chrilith** [comment]
Great thanks!
