### ISSUE TITLE
We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by mathiasrw** [inch-ci/inch_ci-web#81]
Looks awesome with inch_ci - trying to add alasql but end up on this URL https://inch-ci.org/github/agershun/alasql?pending_build=66986 stating that 

> We're sorry, but something went wrong.
> 
> If you are the application owner check the logs for more information.

Can I do something to help out the issue?

**Comment by rrrene** [comment]
Inch tries to scan all JS files in lib and src, which crashes.

You could add a `inch.json` file to your repo containing this:

```
{
  "files": {
    "included": ["dist/alasql.js"]
  }
}
```

That should give you a starting point. If I am mistaken, simply ping me here! :+1:

**Comment by mathiasrw** [comment]
Sweet !

**Comment by mathiasrw** [comment]
Ok, so now I have 
- Pushed the file to a specific branch
- Opened https://inch-ci.org/github/agershun/alasql (its working but stating that its not evaluated yet)
- Selected my branch from the branch dropdown

What I see now is a different error on https://inch-ci.org/github/agershun/alasql/branch/feature/code-quality stating that 

> The page you were looking for doesn't exist.
> 
> You may have mistyped the address or the page may have moved.

Can it be because the branch is named release/code-quality that it somehow messes up the file path?

**Comment by mathiasrw** [comment]
Ok - just testing to see if the error kept comming I placed the inch.json in the branch `develop` - but it did not help. I still get  

> We're sorry, but something went wrong.

on https://inch-ci.org/github/agershun/alasql/branch/develop?pending_build=67022

**Comment by rrrene** [comment]
Mmmh, this seems to be a deeper issue. I will look into it as soon as I can!

**Comment by mathiasrw** [comment]
:+1:

**Comment by rrrene** [comment]
Hi @mathiasrw,

there was an issue with branch names and URL routing that might have caused this and that I fixed today. 

Will close for now. Thx for the bug report! :+1: And *please* re-open if your issue isn't solved!

**Comment by mathiasrw** [comment]
:+1:
