### ISSUE TITLE
Add documentation for adding a badge

### ISSUE THREAD

**Issue by lpil** [inch-ci/inch_ci-web#88]
Hello!

I can't find any information on how to add a badge, and as a result I'm doing something wrong.

I've copied the badge code from another project, changed the path to my repo, yet no luck. Could we get some instructions on the page for a repo on inch? Also, what am I doing wrong? :)

https://github.com/lpil/dogma

**Comment by rrrene** [comment]
Hi, thanks for the heads up! Elixir projects are a bit more complicated on Inch CI and I will try to improve that.

In the meantime, the easiest way to add Elixir projects is through `inch_ex` and its Mix task - [Instructions can be found here](https://github.com/rrrene/inch_ex#adding-a-project-to-inch-ci).

**Comment by lpil** [comment]
I've done that, and when I go to the profile page I have the analysis there, but the badge I've added to my readme doesn't show.

It's likely that I've done something wrong, but I don't know what as the documentation doesn't cover adding the badge.

**Comment by rrrene** [comment]
You are missing the `.svg` part of the badge filename ;-)

**Comment by rrrene** [comment]
Btw, you can just click on the badge here https://inch-ci.org/github/lpil/dogma and customize which version you want!

**Comment by lpil** [comment]
Ah, I see, thank you! I feel very silly. :)
