### ISSUE TITLE
Please add support for PHP

### ISSUE THREAD

**Issue by gabel** [inch-ci/inch_ci-web#91]

**Comment by hexus** [comment]
I'd like this too. In fact, I imagine the entire PHP community would.

**Comment by ganglio** [comment]
I agree! Being able to test documentation quality on a project comes at great advantage for both the dev and the users. Please (please) add support to PHP :smile:

**Comment by vitalyiegorov** [comment]
I totally agree! Please add support to PHP :smile:

**Comment by rrrene** [comment]
Okay, the only problem is that I am not an active PHP coder, so I would need help on this.

What we would need is a PHP documentation parser that can produce machine-readable output like JSON or XML. For example, in JavaScript we use [JSDoc](http://usejsdoc.org/) for this. It parses the documentation, emits JSON which is then parsed by Inch to create the evaluation.

Do you know of any such project for PHP?

**Comment by vitalyiegorov** [comment]
Can u please provide output file for analyzing.

2015-10-29 14:49 GMT+02:00 René Föhring <notifications@github.com>:

> Okay, the only problem is that I am not an active PHP coder, so I would
> need help on this.
>
> What we would need is a PHP documentation parser that can produce
> machine-readable output like JSON or XML. For example, in JavaScript we use
> JSDoc <http://usejsdoc.org/> for this. It parses the documentation, emits
> JSON which is then parsed by Inch to create the evaluation.
>
> Do you know of any such project for PHP?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inch-ci/inch_ci-web/issues/91#issuecomment-152168730>.
>



-- 
С Уважением, Егоров Виталий,
моб.: (050) 414-13-07
skype: vitalyiegorov
vitalyiegorov@gmail.com

**Comment by rrrene** [comment]
Something along these lines would be great:

    {
      "objects": [
        { 
          "source": "src/Quantum/ProxyCacheWarmer.php:15", 
          "fullname": "Quantum.ProxyCacheWarmer.refreshUser",
          "type": "Function", 
          "parameters": ["$user"]
        },
        // ...
      ]
    }

Please note that I know next to nothing about PHP, so my notation of `fullname` maybe wrong (please use whatever notation PHP devs are familar with).

**Comment by rrrene** [comment]
I updated the above comment many times, in case your reading via email!

**Comment by vitalyiegorov** [comment]
Thank u, can u please attach an example of generated JSON file for real project on ruby or javascript?

**Comment by rrrene** [comment]
An example JSON for [Forever](https://github.com/foreverjs/forever) can be found here: https://gist.github.com/rrrene/69c0a81bc748d6fd71a5

**Comment by rrrene** [comment]
And yes: fullname means a unique name in the code base. So I would presume it will be something like  `namespace + class_name + function_name` ...

**Comment by hexus** [comment]
A fully qualified namespace in PHP, with a method, would look something like this:

```
Quantum\ProxyCacheWarmer::refreshUser()
```

**Comment by rrrene** [comment]
Ah, I suspected it would be different from Ruby et al. 

Thx!

**Comment by rugk** [comment]
In PHP documentation is added (in the source) via PHPDOC. This can be parsed by [PHPDocumentor](https://phpdoc.org/) later.

**Comment by Rudloff** [comment]
`phpdoc --template=xml` generates this kind of XML file: https://gist.github.com/Rudloff/f037b01c2397ad5bc407bd7dfadf996b
Would that be something you can parse?

**Comment by vitalyiegorov** [comment]
@rrrene Any success using phpdoc? If i can help in some way  - please tell. I think that you using comments analysis is the last part to make perfect modules/packages. Take a look at [SamsonFramework/Generator](https://github.com/samsonframework/generator) We have scrutinizer and code climate for code quality analysis, we have styleci for coding standards validation, we have travis for builds and code coverage, packagist for dependency management and statistics, the only thing that we are lacking - is comments coverage, I think that code commenting is super very important especially in PHP. So this would give super interest to your project from PHP world if you would be first to implement such kind of CI analysis or I think someone will do it aside.

**Comment by rrrene** [comment]
@vitalyiegorov I will need a free weekend to look at this stuff. We would need to convert the XML to JSON like described above.

**Comment by vitalyiegorov** [comment]
@rrrene Found this package, please take a look at it https://github.com/martinsik/php-doc-parser

**Comment by vitalyiegorov** [comment]
@rrrene  Any success with PHP language?

**Comment by rrrene** [comment]
Sorry, did not find the time. 😞

**Comment by vitalyiegorov** [comment]
Ok, so we have figured out than we can get XML output regarding documentation using [phpdoc](https://phpdoc.org/docs/latest/getting-started/changing-the-look-and-feel.html) cli, can you guide me how to attach this approach to current project or what should be our steps to integrate it into inch-ci logic.

**Comment by rrrene** [comment]
Please re-read the discussion in this issue. We need a PHP CLI which runs `phpdoc` (or something similar) and converts the resulting XML into the described JSON format. That will be a bunch of work.

Sidekiq has nothing to do with that and comes a loooong way down the road, when integrating the to-be-invented Inch for PHP into Inch CI, the webservice. :+1:

**Comment by Saibamen** [comment]
We need this

**Comment by filips123** [comment]
@inch-ci Is there any update? This issue is 4 years old and not active for 1 year. Support for PHP would be needed.

**Comment by devsimsek** [comment]
I totally agree. @inch-ci needs to support php.

**Comment by gabel** [comment]
closing stale issue
