### ISSUE TITLE
Should skip @ignore token

### ISSUE THREAD

**Issue by pandres95** [inch-ci/inch_ci-web#95]
Although this is not going to be in the docs, evaluates it.
---
Re: [B] [module.exports](http://inch-ci.org/github/booljs/booljs-api/branch/master/revision/c5a5b7e2/code_object/1510861) in [BoolJS/booljs-api](http://inch-ci.org/github/booljs/booljs-api)

**Comment by rrrene** [comment]
:+1: will fix in the next release!

**Comment by pandres95** [comment]
:+1: :smile:

**Comment by rrrene** [comment]
Done. :shipit:
