### ISSUE TITLE
[Javascript] ignore istanbul ignores

### ISSUE THREAD

**Issue by fscherwi** [inch-ci/inch_ci-web#97]
Ignore comments such like: ```/* istanbul ignore next */```, because it's no documentation!

See also: https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md#the-interface

**Comment by rrrene** [comment]
So, if I read this correctly Inch should just ignore comments starting with `istanbul ignore` (basically treating them as non-existent)?

**Comment by fscherwi** [comment]
Yes!

**Comment by rrrene** [comment]
Done. :shipit:
