### ISSUE TITLE
The "Show N More" link does not work when viewing branch other than master

### ISSUE THREAD

**Issue by notmessenger** [inch-ci/inch_ci-web#99]
---
Re: [notmessenger/sl-ember-components](http://inch-ci.org/github/notmessenger/sl-ember-components)

**Comment by rrrene** [comment]
Which repo are you looking at? [notmessenger/sl-ember-components](http://inch-ci.org/github/notmessenger/sl-ember-components) does not seem to have any other branches with analysed code in them.

And do you mean "there is a link and I click on it and nothing happens" or "the link is missing"?

**Comment by notmessenger** [comment]
That is the repo but I had removed the other branches before I submitted the issue.  I can add it back if need be.  What I mean is that clicking the link does not expand to show more.  This is because the link does not contain the branch name in it so things are not associated properly.

**Comment by rrrene** [comment]
Ah, I get it. 

Will try to reproduce it locally and fix it. Thanks for the bug report!

**Comment by rrrene** [comment]
Yay, it's only taken me two months to get this done \**sarcasm*\*

Seriuosly, thx again for the bug report and sorry for not resolving this earlier! :+1:
